[build]
  base = ""
  publish = "build/"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://atcoder-for-chinese.netlify.app"
    Access-Control-Allow-Credentials = true
